#include "MonsterModelMap.hpp"
#include "GameMap.hpp"
#include <spdlog/spdlog.h>

const std::string& getMonsterModelFile(const Monster& mon)
{
    static const std::string s_defaultModel = "monkey.obj";

    // Monster type enum → OBJ model file mapping.
    // Generated from crawl monster-type.h (TAG_MAJOR_VERSION 34).
    // To update: g++ -DTAG_MAJOR_VERSION=34 -I. -E monster-type.h
    static const std::unordered_map<int, std::string> s_typeModelMap = {
        { 0, "monkey.obj" }, // MONS_PROGRAM_BUG
        { 1, "monkey.obj" }, // MONS_FRILLED_LIZARD
        { 2, "monkey.obj" }, // MONS_LEOPARD_GECKO
        { 3, "monkey.obj" }, // MONS_IGUANA
        { 4, "monkey.obj" }, // MONS_KOMODO_DRAGON
        { 5, "monkey.obj" }, // MONS_BASILISK
        { 6, "marble_bust_01_1k.obj" }, // MONS_BAT
        { 7, "marble_bust_01_1k.obj" }, // MONS_FIRE_BAT
        { 8, "monkey.obj" }, // MONS_BALL_PYTHON
        { 9, "monkey.obj" }, // MONS_ADDER
        { 10, "monkey.obj" }, // MONS_WATER_MOCCASIN
        { 11, "monkey.obj" }, // MONS_BLACK_MAMBA
        { 12, "monkey.obj" }, // MONS_ANACONDA
        { 13, "monkey.obj" }, // MONS_SEA_SNAKE
        { 14, "monkey.obj" }, // MONS_RAT
        { 15, "monkey.obj" }, // MONS_GREY_RAT
        { 16, "monkey.obj" }, // MONS_RIVER_RAT
        { 17, "monkey.obj" }, // MONS_HELL_RAT
        { 18, "monkey.obj" }, // MONS_LABORATORY_RAT
        { 19, "monkey.obj" }, // MONS_QUOKKA
        { 20, "monkey.obj" }, // MONS_PORCUPINE
        { 21, "concrete_cat_statue_1k.obj" }, // MONS_JACKAL
        { 22, "monkey.obj" }, // MONS_HOUND
        { 23, "monkey.obj" }, // MONS_WAR_DOG
        { 24, "monkey.obj" }, // MONS_WOLF
        { 25, "monkey.obj" }, // MONS_WARG
        { 26, "monkey.obj" }, // MONS_HELL_HOUND
        { 27, "monkey.obj" }, // MONS_HOG
        { 28, "monkey.obj" }, // MONS_HELL_HOG
        { 29, "monkey.obj" }, // MONS_HOLY_SWINE
        { 30, "monkey.obj" }, // MONS_GIANT_SLUG
        { 31, "monkey.obj" }, // MONS_AGATE_SNAIL
        { 32, "monkey.obj" }, // MONS_ELEPHANT_SLUG
        { 33, "monkey.obj" }, // MONS_TYRANT_LEECH
        { 34, "monkey.obj" }, // MONS_BABY_ALLIGATOR
        { 35, "monkey.obj" }, // MONS_ALLIGATOR
        { 36, "monkey.obj" }, // MONS_CROCODILE
        { 37, "monkey.obj" }, // MONS_HYDRA
        { 38, "monkey.obj" }, // MONS_SHEEP
        { 39, "monkey.obj" }, // MONS_YAK
        { 40, "monkey.obj" }, // MONS_DEATH_YAK
        { 41, "monkey.obj" }, // MONS_CATOBLEPAS
        { 42, "monkey.obj" }, // MONS_ELEPHANT
        { 43, "monkey.obj" }, // MONS_DIRE_ELEPHANT
        { 44, "monkey.obj" }, // MONS_HELLEPHANT
        { 45, "monkey.obj" }, // MONS_MANTICORE
        { 46, "monkey.obj" }, // MONS_HIPPOGRIFF
        { 47, "monkey.obj" }, // MONS_GRIFFON
        { 48, "monkey.obj" }, // MONS_BULLFROG
        { 49, "monkey.obj" }, // MONS_CANE_TOAD
        { 50, "monkey.obj" }, // MONS_BLINK_FROG
        { 51, "monkey.obj" }, // MONS_GRIZZLY_BEAR
        { 52, "monkey.obj" }, // MONS_POLAR_BEAR
        { 53, "monkey.obj" }, // MONS_BLACK_BEAR
        { 54, "monkey.obj" }, // MONS_RIBBON_WORM
        { 55, "monkey.obj" }, // MONS_BRAIN_WORM
        { 56, "monkey.obj" }, // MONS_ROCK_WORM
        { 57, "monkey.obj" }, // MONS_SPINY_WORM
        { 58, "monkey.obj" }, // MONS_WYVERN
        { 59, "monkey.obj" }, // MONS_LINDWURM
        { 60, "monkey.obj" }, // MONS_RIME_DRAKE
        { 61, "monkey.obj" }, // MONS_SWAMP_DRAKE
        { 62, "monkey.obj" }, // MONS_DEATH_DRAKE
        { 63, "monkey.obj" }, // MONS_STEAM_DRAGON
        { 64, "monkey.obj" }, // MONS_ACID_DRAGON
        { 65, "monkey.obj" }, // MONS_SWAMP_DRAGON
        { 66, "monkey.obj" }, // MONS_FIRE_DRAGON
        { 67, "monkey.obj" }, // MONS_ICE_DRAGON
        { 68, "monkey.obj" }, // MONS_SHADOW_DRAGON
        { 69, "monkey.obj" }, // MONS_STORM_DRAGON
        { 70, "monkey.obj" }, // MONS_BONE_DRAGON
        { 71, "monkey.obj" }, // MONS_QUICKSILVER_DRAGON
        { 72, "monkey.obj" }, // MONS_IRON_DRAGON
        { 73, "monkey.obj" }, // MONS_GOLDEN_DRAGON
        { 74, "monkey.obj" }, // MONS_PEARL_DRAGON
        { 75, "monkey.obj" }, // MONS_ENDOPLASM
        { 76, "monkey.obj" }, // MONS_JELLY
        { 77, "monkey.obj" }, // MONS_BROWN_OOZE
        { 78, "monkey.obj" }, // MONS_GIANT_AMOEBA
        { 79, "monkey.obj" }, // MONS_AZURE_JELLY
        { 80, "monkey.obj" }, // MONS_DEATH_OOZE
        { 81, "monkey.obj" }, // MONS_ACID_BLOB
        { 82, "monkey.obj" }, // MONS_SLIME_CREATURE
        { 83, "monkey.obj" }, // MONS_PULSATING_LUMP
        { 84, "monkey.obj" }, // MONS_GLASS_EYE
        { 85, "monkey.obj" }, // MONS_EYE_OF_DRAINING
        { 86, "monkey.obj" }, // MONS_SHINING_EYE
        { 87, "monkey.obj" }, // MONS_EYE_OF_DEVASTATION
        { 88, "monkey.obj" }, // MONS_GREAT_ORB_OF_EYES
        { 89, "monkey.obj" }, // MONS_GLOWING_ORANGE_BRAIN
        { 90, "monkey.obj" }, // MONS_DANCING_WEAPON
        { 91, "monkey.obj" }, // MONS_HARPY
        { 92, "monkey.obj" }, // MONS_RAVEN
        { 93, "monkey.obj" }, // MONS_FIRE_CRAB
        { 94, "monkey.obj" }, // MONS_HOMUNCULUS
        { 95, "monkey.obj" }, // MONS_SOUPLING
        { 96, "monkey.obj" }, // MONS_BUTTERFLY
        { 97, "monkey.obj" }, // MONS_ANT_LARVA
        { 98, "monkey.obj" }, // MONS_WORKER_ANT
        { 99, "monkey.obj" }, // MONS_SOLDIER_ANT
        { 100, "monkey.obj" }, // MONS_QUEEN_ANT
        { 101, "monkey.obj" }, // MONS_KILLER_BEE
        { 102, "monkey.obj" }, // MONS_QUEEN_BEE
        { 103, "monkey.obj" }, // MONS_VAMPIRE_MOSQUITO
        { 104, "monkey.obj" }, // MONS_BUMBLEBEE
        { 105, "monkey.obj" }, // MONS_WASP
        { 106, "monkey.obj" }, // MONS_HORNET
        { 107, "monkey.obj" }, // MONS_BEETLE
        { 108, "monkey.obj" }, // MONS_BORING_BEETLE
        { 109, "monkey.obj" }, // MONS_BOULDER_BEETLE
        { 110, "icosphere.obj" }, // MONS_GIANT_COCKROACH
        { 111, "monkey.obj" }, // MONS_GIANT_CENTIPEDE
        { 112, "monkey.obj" }, // MONS_GIANT_MITE
        { 113, "monkey.obj" }, // MONS_SPIDER
        { 114, "monkey.obj" }, // MONS_WOLF_SPIDER
        { 115, "monkey.obj" }, // MONS_TRAPDOOR_SPIDER
        { 116, "monkey.obj" }, // MONS_JUMPING_SPIDER
        { 117, "monkey.obj" }, // MONS_ORB_SPIDER
        { 118, "monkey.obj" }, // MONS_TARANTELLA
        { 119, "monkey.obj" }, // MONS_REDBACK
        { 120, "monkey.obj" }, // MONS_SCORPION
        { 121, "monkey.obj" }, // MONS_EMPEROR_SCORPION
        { 122, "monkey.obj" }, // MONS_MOTH
        { 123, "monkey.obj" }, // MONS_MOTH_OF_SUPPRESSION
        { 124, "monkey.obj" }, // MONS_GHOST_MOTH
        { 125, "monkey.obj" }, // MONS_MOTH_OF_WRATH
        { 126, "monkey.obj" }, // MONS_DEMONIC_CRAWLER
        { 127, "monkey.obj" }, // MONS_SNAPPING_TURTLE
        { 128, "monkey.obj" }, // MONS_ALLIGATOR_SNAPPING_TURTLE
        { 129, "monkey.obj" }, // MONS_GNOME
        { 130, "monkey.obj" }, // MONS_HALFLING
        { 131, "monkey.obj" }, // MONS_FELID
        { 132, "monkey.obj" }, // MONS_VAMPIRE_BAT
        { 133, "monkey.obj" }, // MONS_DEMIGOD
        { 134, "monkey.obj" }, // MONS_DEMONSPAWN
        { 135, "monkey.obj" }, // MONS_GARGOYLE
        { 136, "monkey.obj" }, // MONS_WAR_GARGOYLE
        { 137, "monkey.obj" }, // MONS_MOLTEN_GARGOYLE
        { 138, "monkey.obj" }, // MONS_UGLY_THING
        { 139, "monkey.obj" }, // MONS_VERY_UGLY_THING
        { 140, "monkey.obj" }, // MONS_ICE_BEAST
        { 141, "monkey.obj" }, // MONS_SKY_BEAST
        { 142, "monkey.obj" }, // MONS_GUARDIAN_SPHINX
        { 143, "monkey.obj" }, // MONS_ORB_GUARDIAN
        { 144, "monkey.obj" }, // MONS_GOLEM
        { 145, "monkey.obj" }, // MONS_CLAY_GOLEM
        { 146, "monkey.obj" }, // MONS_WOOD_GOLEM
        { 147, "monkey.obj" }, // MONS_STONE_GOLEM
        { 148, "monkey.obj" }, // MONS_IRON_GOLEM
        { 149, "monkey.obj" }, // MONS_CRYSTAL_GUARDIAN
        { 150, "monkey.obj" }, // MONS_TOENAIL_GOLEM
        { 151, "monkey.obj" }, // MONS_ELECTRIC_GOLEM
        { 152, "monkey.obj" }, // MONS_ORB_OF_FIRE
        { 153, "monkey.obj" }, // MONS_EARTH_ELEMENTAL
        { 154, "monkey.obj" }, // MONS_FIRE_ELEMENTAL
        { 155, "monkey.obj" }, // MONS_AIR_ELEMENTAL
        { 156, "monkey.obj" }, // MONS_TWISTER
        { 157, "monkey.obj" }, // MONS_GOLDEN_EYE
        { 158, "monkey.obj" }, // MONS_FIRE_VORTEX
        { 159, "monkey.obj" }, // MONS_SPATIAL_VORTEX
        { 160, "monkey.obj" }, // MONS_INSUBSTANTIAL_WISP
        { 161, "monkey.obj" }, // MONS_VAPOUR
        { 162, "monkey.obj" }, // MONS_INEPT_ITEM_MIMIC
        { 163, "monkey.obj" }, // MONS_ITEM_MIMIC
        { 164, "monkey.obj" }, // MONS_RAVENOUS_ITEM_MIMIC
        { 165, "monkey.obj" }, // MONS_MONSTROUS_ITEM_MIMIC
        { 166, "monkey.obj" }, // MONS_INEPT_FEATURE_MIMIC
        { 167, "monkey.obj" }, // MONS_FEATURE_MIMIC
        { 168, "monkey.obj" }, // MONS_RAVENOUS_FEATURE_MIMIC
        { 169, "monkey.obj" }, // MONS_MONSTROUS_FEATURE_MIMIC
        { 170, "monkey.obj" }, // MONS_TOADSTOOL
        { 171, "monkey.obj" }, // MONS_FUNGUS
        { 172, "monkey.obj" }, // MONS_WANDERING_MUSHROOM
        { 173, "monkey.obj" }, // MONS_PLANT
        { 174, "monkey.obj" }, // MONS_OKLOB_SAPLING
        { 175, "monkey.obj" }, // MONS_OKLOB_PLANT
        { 176, "monkey.obj" }, // MONS_BUSH
        { 177, "monkey.obj" }, // MONS_SCRUB_NETTLE
        { 178, "monkey.obj" }, // MONS_BALLISTOMYCETE_SPORE
        { 179, "monkey.obj" }, // MONS_BALLISTOMYCETE
        { 180, "monkey.obj" }, // MONS_HYPERACTIVE_BALLISTOMYCETE
        { 181, "monkey.obj" }, // MONS_GOBLIN
        { 182, "monkey.obj" }, // MONS_HOBGOBLIN
        { 183, "bull_head_1k.obj" }, // MONS_GNOLL
        { 184, "bull_head_1k.obj" }, // MONS_GNOLL_BOUDA
        { 185, "bull_head_1k.obj" }, // MONS_GNOLL_SERGEANT
        { 186, "monkey.obj" }, // MONS_BOGGART
        { 187, "rubber_duck_toy_1k.obj" }, // MONS_KOBOLD
        { 188, "rubber_duck_toy_1k.obj" }, // MONS_KOBOLD_BRIGAND
        { 189, "rubber_duck_toy_1k.obj" }, // MONS_KOBOLD_DEMONOLOGIST
        { 190, "monkey.obj" }, // MONS_ORC
        { 191, "monkey.obj" }, // MONS_ORC_WARRIOR
        { 192, "monkey.obj" }, // MONS_ORC_PRIEST
        { 193, "monkey.obj" }, // MONS_ORC_HIGH_PRIEST
        { 194, "monkey.obj" }, // MONS_ORC_WIZARD
        { 195, "monkey.obj" }, // MONS_ORC_KNIGHT
        { 196, "monkey.obj" }, // MONS_ORC_SORCERER
        { 197, "monkey.obj" }, // MONS_ORC_WARLORD
        { 198, "monkey.obj" }, // MONS_DWARF
        { 199, "monkey.obj" }, // MONS_DEEP_DWARF
        { 200, "monkey.obj" }, // MONS_DEEP_DWARF_SCION
        { 201, "monkey.obj" }, // MONS_DEEP_DWARF_ARTIFICER
        { 202, "monkey.obj" }, // MONS_DEEP_DWARF_NECROMANCER
        { 203, "monkey.obj" }, // MONS_DEEP_DWARF_BERSERKER
        { 204, "monkey.obj" }, // MONS_DEATH_KNIGHT
        { 205, "monkey.obj" }, // MONS_UNBORN
        { 206, "monkey.obj" }, // MONS_ELF
        { 207, "monkey.obj" }, // MONS_DEEP_ELF_SOLDIER
        { 208, "monkey.obj" }, // MONS_DEEP_ELF_FIGHTER
        { 209, "monkey.obj" }, // MONS_DEEP_ELF_KNIGHT
        { 210, "monkey.obj" }, // MONS_DEEP_ELF_FIRE_MAGE
        { 211, "monkey.obj" }, // MONS_DEEP_ELF_SUMMONER
        { 212, "monkey.obj" }, // MONS_DEEP_ELF_CONJURER
        { 213, "monkey.obj" }, // MONS_DEEP_ELF_PRIEST
        { 214, "monkey.obj" }, // MONS_DEEP_ELF_HIGH_PRIEST
        { 215, "monkey.obj" }, // MONS_DEEP_ELF_DEMONOLOGIST
        { 216, "monkey.obj" }, // MONS_DEEP_ELF_ANNIHILATOR
        { 217, "monkey.obj" }, // MONS_DEEP_ELF_SORCERER
        { 218, "monkey.obj" }, // MONS_DEEP_ELF_DEATH_MAGE
        { 219, "monkey.obj" }, // MONS_DEEP_ELF_BLADEMASTER
        { 220, "monkey.obj" }, // MONS_DEEP_ELF_MASTER_ARCHER
        { 221, "monkey.obj" }, // MONS_SPRIGGAN
        { 222, "monkey.obj" }, // MONS_SPRIGGAN_DRUID
        { 223, "monkey.obj" }, // MONS_SPRIGGAN_ASSASSIN
        { 224, "monkey.obj" }, // MONS_SPRIGGAN_RIDER
        { 225, "monkey.obj" }, // MONS_SPRIGGAN_BERSERKER
        { 226, "monkey.obj" }, // MONS_SPRIGGAN_DEFENDER
        { 227, "monkey.obj" }, // MONS_SPRIGGAN_AIR_MAGE
        { 228, "monkey.obj" }, // MONS_FIREFLY
        { 229, "monkey.obj" }, // MONS_TENGU
        { 230, "monkey.obj" }, // MONS_MINOTAUR
        { 231, "monkey.obj" }, // MONS_NAGA
        { 232, "monkey.obj" }, // MONS_NAGA_WARRIOR
        { 233, "monkey.obj" }, // MONS_NAGA_MAGE
        { 234, "monkey.obj" }, // MONS_NAGARAJA
        { 235, "monkey.obj" }, // MONS_GUARDIAN_SERPENT
        { 236, "monkey.obj" }, // MONS_OCTOPODE
        { 237, "monkey.obj" }, // MONS_MERFOLK
        { 238, "monkey.obj" }, // MONS_MERFOLK_SIREN
        { 239, "monkey.obj" }, // MONS_MERFOLK_AVATAR
        { 240, "monkey.obj" }, // MONS_MERFOLK_IMPALER
        { 241, "monkey.obj" }, // MONS_MERFOLK_AQUAMANCER
        { 242, "monkey.obj" }, // MONS_MERFOLK_JAVELINEER
        { 243, "monkey.obj" }, // MONS_CENTAUR
        { 244, "monkey.obj" }, // MONS_CENTAUR_WARRIOR
        { 245, "monkey.obj" }, // MONS_YAKTAUR
        { 246, "monkey.obj" }, // MONS_YAKTAUR_CAPTAIN
        { 247, "monkey.obj" }, // MONS_OGRE
        { 248, "monkey.obj" }, // MONS_TWO_HEADED_OGRE
        { 249, "monkey.obj" }, // MONS_OGRE_MAGE
        { 250, "monkey.obj" }, // MONS_TROLL
        { 251, "monkey.obj" }, // MONS_ROCK_TROLL
        { 252, "monkey.obj" }, // MONS_IRON_TROLL
        { 253, "monkey.obj" }, // MONS_DEEP_TROLL
        { 254, "monkey.obj" }, // MONS_GIANT
        { 255, "monkey.obj" }, // MONS_HILL_GIANT
        { 256, "monkey.obj" }, // MONS_CYCLOPS
        { 257, "monkey.obj" }, // MONS_ETTIN
        { 258, "monkey.obj" }, // MONS_STONE_GIANT
        { 259, "monkey.obj" }, // MONS_FIRE_GIANT
        { 260, "monkey.obj" }, // MONS_FROST_GIANT
        { 261, "monkey.obj" }, // MONS_TITAN
        { 262, "monkey.obj" }, // MONS_HUMAN
        { 263, "monkey.obj" }, // MONS_SLAVE
        { 264, "monkey.obj" }, // MONS_HELL_KNIGHT
        { 265, "monkey.obj" }, // MONS_NECROMANCER
        { 266, "monkey.obj" }, // MONS_OCCULTIST
        { 267, "monkey.obj" }, // MONS_VAULT_GUARD
        { 268, "monkey.obj" }, // MONS_KILLER_KLOWN
        { 269, "monkey.obj" }, // MONS_SHAPESHIFTER
        { 270, "monkey.obj" }, // MONS_GLOWING_SHAPESHIFTER
        { 271, "monkey.obj" }, // MONS_DRACONIAN
        { 272, "monkey.obj" }, // MONS_BLACK_DRACONIAN
        { 273, "monkey.obj" }, // MONS_MOTTLED_DRACONIAN
        { 274, "monkey.obj" }, // MONS_YELLOW_DRACONIAN
        { 275, "monkey.obj" }, // MONS_GREEN_DRACONIAN
        { 276, "monkey.obj" }, // MONS_PURPLE_DRACONIAN
        { 277, "monkey.obj" }, // MONS_RED_DRACONIAN
        { 278, "monkey.obj" }, // MONS_WHITE_DRACONIAN
        { 279, "monkey.obj" }, // MONS_GREY_DRACONIAN
        { 280, "monkey.obj" }, // MONS_PALE_DRACONIAN
        { 281, "monkey.obj" }, // MONS_DRACONIAN_STORMCALLER
        { 282, "monkey.obj" }, // MONS_DRACONIAN_MONK
        { 283, "monkey.obj" }, // MONS_DRACONIAN_ZEALOT
        { 284, "monkey.obj" }, // MONS_DRACONIAN_SHIFTER
        { 285, "monkey.obj" }, // MONS_DRACONIAN_ANNIHILATOR
        { 286, "monkey.obj" }, // MONS_DRACONIAN_KNIGHT
        { 287, "monkey.obj" }, // MONS_DRACONIAN_SCORCHER
        { 288, "monkey.obj" }, // MONS_LAVA_WORM
        { 289, "monkey.obj" }, // MONS_LAVA_FISH
        { 290, "monkey.obj" }, // MONS_LAVA_SNAKE
        { 291, "monkey.obj" }, // MONS_SALAMANDER
        { 292, "monkey.obj" }, // MONS_BIG_FISH
        { 293, "monkey.obj" }, // MONS_GIANT_GOLDFISH
        { 294, "monkey.obj" }, // MONS_ELECTRIC_EEL
        { 295, "monkey.obj" }, // MONS_JELLYFISH
        { 296, "monkey.obj" }, // MONS_WATER_ELEMENTAL
        { 297, "monkey.obj" }, // MONS_SWAMP_WORM
        { 298, "monkey.obj" }, // MONS_SHARK
        { 299, "monkey.obj" }, // MONS_KRAKEN
        { 300, "monkey.obj" }, // MONS_KRAKEN_TENTACLE
        { 301, "monkey.obj" }, // MONS_KRAKEN_TENTACLE_SEGMENT
        { 302, "monkey.obj" }, // MONS_ORANGE_STATUE
        { 303, "monkey.obj" }, // MONS_OBSIDIAN_STATUE
        { 304, "monkey.obj" }, // MONS_ICE_STATUE
        { 305, "monkey.obj" }, // MONS_STATUE
        { 306, "monkey.obj" }, // MONS_TRAINING_DUMMY
        { 307, "monkey.obj" }, // MONS_LIGHTNING_SPIRE
        { 308, "monkey.obj" }, // MONS_CRIMSON_IMP
        { 309, "monkey.obj" }, // MONS_QUASIT
        { 310, "monkey.obj" }, // MONS_WHITE_IMP
        { 311, "monkey.obj" }, // MONS_LEMURE
        { 312, "monkey.obj" }, // MONS_UFETUBUS
        { 313, "monkey.obj" }, // MONS_IRON_IMP
        { 314, "monkey.obj" }, // MONS_SHADOW_IMP
        { 315, "monkey.obj" }, // MONS_RED_DEVIL
        { 316, "monkey.obj" }, // MONS_ROTTING_DEVIL
        { 317, "monkey.obj" }, // MONS_HELLWING
        { 318, "monkey.obj" }, // MONS_SIXFIRHY
        { 319, "monkey.obj" }, // MONS_NEQOXEC
        { 320, "monkey.obj" }, // MONS_ORANGE_DEMON
        { 321, "monkey.obj" }, // MONS_SMOKE_DEMON
        { 322, "monkey.obj" }, // MONS_YNOXINUL
        { 323, "monkey.obj" }, // MONS_CHAOS_SPAWN
        { 324, "monkey.obj" }, // MONS_HELLION
        { 325, "monkey.obj" }, // MONS_LOROCYPROCA
        { 326, "monkey.obj" }, // MONS_TORMENTOR
        { 327, "monkey.obj" }, // MONS_REAPER
        { 328, "monkey.obj" }, // MONS_SOUL_EATER
        { 329, "monkey.obj" }, // MONS_ICE_DEVIL
        { 330, "monkey.obj" }, // MONS_BLUE_DEVIL
        { 331, "monkey.obj" }, // MONS_SIN_BEAST
        { 332, "monkey.obj" }, // MONS_RUST_DEVIL
        { 333, "monkey.obj" }, // MONS_EXECUTIONER
        { 334, "monkey.obj" }, // MONS_GREEN_DEATH
        { 335, "monkey.obj" }, // MONS_BLIZZARD_DEMON
        { 336, "monkey.obj" }, // MONS_BALRUG
        { 337, "monkey.obj" }, // MONS_CACODEMON
        { 338, "monkey.obj" }, // MONS_SUN_DEMON
        { 339, "monkey.obj" }, // MONS_SHADOW_DEMON
        { 340, "monkey.obj" }, // MONS_HELL_SENTINEL
        { 341, "monkey.obj" }, // MONS_BRIMSTONE_FIEND
        { 342, "monkey.obj" }, // MONS_ICE_FIEND
        { 343, "monkey.obj" }, // MONS_TZITZIMITL
        { 344, "monkey.obj" }, // MONS_PANDEMONIUM_LORD
        { 345, "monkey.obj" }, // MONS_EFREET
        { 346, "monkey.obj" }, // MONS_RAKSHASA
        { 347, "monkey.obj" }, // MONS_RAKSHASA_FAKE
        { 348, "monkey.obj" }, // MONS_UNSEEN_HORROR
        { 349, "monkey.obj" }, // MONS_TENTACLED_STARSPAWN
        { 350, "monkey.obj" }, // MONS_LURKING_HORROR
        { 351, "monkey.obj" }, // MONS_THRASHING_HORROR
        { 352, "monkey.obj" }, // MONS_STARCURSED_MASS
        { 353, "monkey.obj" }, // MONS_ANCIENT_ZYME
        { 354, "monkey.obj" }, // MONS_WRETCHED_STAR
        { 355, "monkey.obj" }, // MONS_ELDRITCH_TENTACLE
        { 356, "monkey.obj" }, // MONS_ELDRITCH_TENTACLE_SEGMENT
        { 357, "monkey.obj" }, // MONS_TENTACLED_MONSTROSITY
        { 358, "monkey.obj" }, // MONS_ABOMINATION_SMALL
        { 359, "monkey.obj" }, // MONS_ABOMINATION_LARGE
        { 360, "monkey.obj" }, // MONS_CRAWLING_CORPSE
        { 361, "monkey.obj" }, // MONS_MACABRE_MASS
        { 362, "monkey.obj" }, // MONS_PLAGUE_SHAMBLER
        { 363, "monkey.obj" }, // MONS_NECROPHAGE
        { 364, "monkey.obj" }, // MONS_GHOUL
        { 365, "monkey.obj" }, // MONS_FLAMING_CORPSE
        { 366, "monkey.obj" }, // MONS_MUMMY
        { 367, "monkey.obj" }, // MONS_BOG_BODY
        { 368, "monkey.obj" }, // MONS_GUARDIAN_MUMMY
        { 369, "monkey.obj" }, // MONS_ROYAL_MUMMY
        { 370, "monkey.obj" }, // MONS_MUMMY_PRIEST
        { 371, "monkey.obj" }, // MONS_VAMPIRE
        { 372, "monkey.obj" }, // MONS_VAMPIRE_KNIGHT
        { 373, "monkey.obj" }, // MONS_VAMPIRE_MAGE
        { 374, "monkey.obj" }, // MONS_GHOST
        { 375, "monkey.obj" }, // MONS_PHANTOM
        { 376, "monkey.obj" }, // MONS_SHADOWGHAST
        { 377, "monkey.obj" }, // MONS_HUNGRY_GHOST
        { 378, "monkey.obj" }, // MONS_FLAYED_GHOST
        { 379, "monkey.obj" }, // MONS_WIGHT
        { 380, "monkey.obj" }, // MONS_WRAITH
        { 381, "monkey.obj" }, // MONS_FREEZING_WRAITH
        { 382, "monkey.obj" }, // MONS_SHADOW_WRAITH
        { 383, "monkey.obj" }, // MONS_SILENT_SPECTRE
        { 384, "monkey.obj" }, // MONS_EIDOLON
        { 385, "monkey.obj" }, // MONS_LAUGHING_SKULL
        { 386, "monkey.obj" }, // MONS_SKELETAL_WARRIOR
        { 387, "monkey.obj" }, // MONS_PHANTASMAL_WARRIOR
        { 388, "monkey.obj" }, // MONS_LICH
        { 389, "monkey.obj" }, // MONS_ANCIENT_LICH
        { 390, "monkey.obj" }, // MONS_DEATH_COB
        { 391, "monkey.obj" }, // MONS_CURSE_TOE
        { 392, "monkey.obj" }, // MONS_CURSE_SKULL
        { 393, "monkey.obj" }, // MONS_PROFANE_SERVITOR
        { 394, "monkey.obj" }, // MONS_SKELETON_SMALL
        { 395, "monkey.obj" }, // MONS_SKELETON_LARGE
        { 396, "monkey.obj" }, // MONS_ZOMBIE_SMALL
        { 397, "monkey.obj" }, // MONS_ZOMBIE_LARGE
        { 398, "monkey.obj" }, // MONS_SPECTRAL_THING
        { 399, "monkey.obj" }, // MONS_SIMULACRUM_SMALL
        { 400, "monkey.obj" }, // MONS_SIMULACRUM_LARGE
        { 401, "monkey.obj" }, // MONS_ANGEL
        { 402, "monkey.obj" }, // MONS_DAEVA
        { 403, "monkey.obj" }, // MONS_CHERUB
        { 404, "monkey.obj" }, // MONS_SERAPH
        { 405, "monkey.obj" }, // MONS_PHOENIX
        { 406, "monkey.obj" }, // MONS_SILVER_STAR
        { 407, "monkey.obj" }, // MONS_BLESSED_TOE
        { 408, "monkey.obj" }, // MONS_SHEDU
        { 409, "monkey.obj" }, // MONS_OPHAN
        { 410, "monkey.obj" }, // MONS_SPIRIT
        { 411, "monkey.obj" }, // MONS_PALADIN
        { 412, "monkey.obj" }, // MONS_APIS
        { 413, "monkey.obj" }, // MONS_GERYON
        { 414, "monkey.obj" }, // MONS_DISPATER
        { 415, "monkey.obj" }, // MONS_ASMODEUS
        { 416, "monkey.obj" }, // MONS_ANTAEUS
        { 417, "monkey.obj" }, // MONS_ERESHKIGAL
        { 418, "monkey.obj" }, // MONS_ROYAL_JELLY
        { 419, "monkey.obj" }, // MONS_ENCHANTRESS
        { 420, "monkey.obj" }, // MONS_MNOLEG
        { 421, "monkey.obj" }, // MONS_LOM_LOBON
        { 422, "monkey.obj" }, // MONS_CEREBOV
        { 423, "monkey.obj" }, // MONS_GLOORX_VLOQ
        { 424, "monkey.obj" }, // MONS_SERPENT_OF_HELL
        { 425, "monkey.obj" }, // MONS_IJYB
        { 426, "monkey.obj" }, // MONS_JESSICA
        { 427, "monkey.obj" }, // MONS_SIGMUND
        { 428, "monkey.obj" }, // MONS_TERENCE
        { 429, "monkey.obj" }, // MONS_BLORKULA_THE_ORCULA
        { 430, "monkey.obj" }, // MONS_EDMUND
        { 431, "monkey.obj" }, // MONS_PSYCHE
        { 432, "monkey.obj" }, // MONS_EROLCHA
        { 433, "monkey.obj" }, // MONS_DONALD
        { 434, "monkey.obj" }, // MONS_URUG
        { 435, "monkey.obj" }, // MONS_JOSEPH
        { 436, "monkey.obj" }, // MONS_SNORG
        { 437, "monkey.obj" }, // MONS_ERICA
        { 438, "monkey.obj" }, // MONS_JOSEPHINE
        { 439, "monkey.obj" }, // MONS_HAROLD
        { 440, "monkey.obj" }, // MONS_AGNES
        { 441, "monkey.obj" }, // MONS_MAUD
        { 442, "monkey.obj" }, // MONS_LOUISE
        { 443, "monkey.obj" }, // MONS_FRANCES
        { 444, "monkey.obj" }, // MONS_RUPERT
        { 445, "monkey.obj" }, // MONS_WIGLAF
        { 446, "monkey.obj" }, // MONS_XTAHUA
        { 447, "monkey.obj" }, // MONS_NORRIS
        { 448, "monkey.obj" }, // MONS_FREDERICK
        { 449, "monkey.obj" }, // MONS_MARGERY
        { 450, "monkey.obj" }, // MONS_BORIS
        { 451, "monkey.obj" }, // MONS_POLYPHEMUS
        { 452, "monkey.obj" }, // MONS_MURRAY
        { 453, "monkey.obj" }, // MONS_TIAMAT
        { 454, "monkey.obj" }, // MONS_ROXANNE
        { 455, "monkey.obj" }, // MONS_SONJA
        { 456, "monkey.obj" }, // MONS_EUSTACHIO
        { 457, "monkey.obj" }, // MONS_AZRAEL
        { 458, "monkey.obj" }, // MONS_ILSUIW
        { 459, "monkey.obj" }, // MONS_PRINCE_RIBBIT
        { 460, "monkey.obj" }, // MONS_NERGALLE
        { 461, "monkey.obj" }, // MONS_SAINT_ROKA
        { 462, "monkey.obj" }, // MONS_NESSOS
        { 463, "monkey.obj" }, // MONS_LERNAEAN_HYDRA
        { 464, "monkey.obj" }, // MONS_DISSOLUTION
        { 465, "monkey.obj" }, // MONS_KIRKE
        { 466, "monkey.obj" }, // MONS_GRUM
        { 467, "monkey.obj" }, // MONS_PARGI
        { 468, "monkey.obj" }, // MONS_MENKAURE
        { 469, "monkey.obj" }, // MONS_DUVESSA
        { 470, "monkey.obj" }, // MONS_DOWAN
        { 471, "monkey.obj" }, // MONS_GASTRONOK
        { 472, "monkey.obj" }, // MONS_MAURICE
        { 473, "monkey.obj" }, // MONS_KHUFU
        { 474, "monkey.obj" }, // MONS_NIKOLA
        { 475, "monkey.obj" }, // MONS_AIZUL
        { 476, "monkey.obj" }, // MONS_PIKEL
        { 477, "monkey.obj" }, // MONS_CRAZY_YIUF
        { 478, "monkey.obj" }, // MONS_MENNAS
        { 479, "monkey.obj" }, // MONS_MARA
        { 480, "monkey.obj" }, // MONS_MARA_FAKE
        { 481, "monkey.obj" }, // MONS_GRINDER
        { 482, "monkey.obj" }, // MONS_JORY
        { 483, "monkey.obj" }, // MONS_IGNACIO
        { 484, "monkey.obj" }, // MONS_ARACHNE
        { 485, "monkey.obj" }, // MONS_CHUCK
        { 486, "monkey.obj" }, // MONS_IRON_GIANT
        { 487, "monkey.obj" }, // MONS_NELLIE
        { 488, "monkey.obj" }, // MONS_IRON_ELEMENTAL
        { 489, "monkey.obj" }, // MONS_PLAYER_ILLUSION
        { 490, "monkey.obj" }, // MONS_PLAYER_GHOST
        { 491, "monkey.obj" }, // MONS_BALL_LIGHTNING
        { 492, "monkey.obj" }, // MONS_ORB_OF_DESTRUCTION
        { 493, "monkey.obj" }, // MONS_PILLAR_OF_SALT
        { 494, "monkey.obj" }, // MONS_HELL_LORD
        { 495, "monkey.obj" }, // MONS_MERGED_SLIME_CREATURE
        { 496, "monkey.obj" }, // MONS_SENSED
        { 497, "monkey.obj" }, // MONS_SENSED_TRIVIAL
        { 498, "monkey.obj" }, // MONS_SENSED_EASY
        { 499, "monkey.obj" }, // MONS_SENSED_TOUGH
        { 500, "monkey.obj" }, // MONS_SENSED_NASTY
        { 501, "monkey.obj" }, // MONS_SENSED_FRIENDLY
        { 502, "monkey.obj" }, // MONS_PLAYER
        { 503, "monkey.obj" }, // MONS_TEST_SPAWNER
        { 504, "monkey.obj" }, // MONS_SERPENT_OF_HELL_COCYTUS
        { 505, "monkey.obj" }, // MONS_SERPENT_OF_HELL_DIS
        { 506, "monkey.obj" }, // MONS_SERPENT_OF_HELL_TARTARUS
        { 507, "monkey.obj" }, // MONS_HELLBINDER
        { 508, "monkey.obj" }, // MONS_CLOUD_MAGE
        { 509, "monkey.obj" }, // MONS_ANIMATED_TREE
        { 510, "monkey.obj" }, // MONS_BEAR
        { 511, "monkey.obj" }, // MONS_ELEMENTAL
        { 512, "monkey.obj" }, // MONS_FANNAR
        { 513, "monkey.obj" }, // MONS_APOCALYPSE_CRAB
        { 514, "monkey.obj" }, // MONS_STARSPAWN_TENTACLE
        { 515, "monkey.obj" }, // MONS_STARSPAWN_TENTACLE_SEGMENT
        { 516, "monkey.obj" }, // MONS_SPATIAL_MAELSTROM
        { 517, "monkey.obj" }, // MONS_CHAOS_BUTTERFLY
        { 518, "monkey.obj" }, // MONS_JORGRUN
        { 519, "monkey.obj" }, // MONS_LAMIA
        { 520, "monkey.obj" }, // MONS_FULMINANT_PRISM
        { 521, "monkey.obj" }, // MONS_BATTLESPHERE
        { 522, "monkey.obj" }, // MONS_GIANT_LIZARD
        { 523, "monkey.obj" }, // MONS_DRAKE
        { 524, "monkey.obj" }, // MONS_PLAYER_SHADOW
        { 525, "monkey.obj" }, // MONS_DEEP_TROLL_EARTH_MAGE
        { 526, "monkey.obj" }, // MONS_DEEP_TROLL_SHAMAN
        { 527, "monkey.obj" }, // MONS_DIAMOND_OBELISK
        { 528, "monkey.obj" }, // MONS_VAULT_SENTINEL
        { 529, "monkey.obj" }, // MONS_VAULT_WARDEN
        { 530, "monkey.obj" }, // MONS_IRONBOUND_CONVOKER
        { 531, "monkey.obj" }, // MONS_IRONBOUND_PRESERVER
        { 532, "monkey.obj" }, // MONS_ZOMBIE
        { 533, "monkey.obj" }, // MONS_SKELETON
        { 534, "monkey.obj" }, // MONS_SIMULACRUM
        { 535, "monkey.obj" }, // MONS_ANCIENT_CHAMPION
        { 536, "monkey.obj" }, // MONS_REVENANT_SOULMONGER
        { 537, "monkey.obj" }, // MONS_LOST_SOUL
        { 538, "monkey.obj" }, // MONS_JIANGSHI
        { 539, "monkey.obj" }, // MONS_DJINNI
        { 540, "monkey.obj" }, // MONS_LAVA_ORC
        { 541, "monkey.obj" }, // MONS_DRYAD
        { 542, "monkey.obj" }, // MONS_WIND_DRAKE
        { 543, "monkey.obj" }, // MONS_FAUN
        { 544, "monkey.obj" }, // MONS_SATYR
        { 545, "monkey.obj" }, // MONS_PAN
        { 546, "monkey.obj" }, // MONS_TENGU_WARRIOR
        { 547, "monkey.obj" }, // MONS_TENGU_CONJURER
        { 548, "monkey.obj" }, // MONS_TENGU_REAVER
        { 549, "monkey.obj" }, // MONS_SPRIGGAN_ENCHANTER
        { 550, "monkey.obj" }, // MONS_SOJOBO
        { 551, "monkey.obj" }, // MONS_CHIMERA
        { 552, "monkey.obj" }, // MONS_SNAPLASHER_VINE
        { 553, "monkey.obj" }, // MONS_SNAPLASHER_VINE_SEGMENT
        { 554, "monkey.obj" }, // MONS_THORN_HUNTER
        { 555, "monkey.obj" }, // MONS_BRIAR_PATCH
        { 556, "monkey.obj" }, // MONS_SPIRIT_WOLF
        { 557, "monkey.obj" }, // MONS_ANCIENT_BEAR
        { 558, "monkey.obj" }, // MONS_WATER_NYMPH
        { 559, "monkey.obj" }, // MONS_SHAMBLING_MANGROVE
        { 560, "monkey.obj" }, // MONS_THORN_LOTUS
        { 561, "monkey.obj" }, // MONS_SPECTRAL_WEAPON
        { 562, "monkey.obj" }, // MONS_ELEMENTAL_WELLSPRING
        { 563, "monkey.obj" }, // MONS_POLYMOTH
        { 564, "monkey.obj" }, // MONS_DEATHCAP
        { 565, "monkey.obj" }, // MONS_IGNIS
        { 566, "monkey.obj" }, // MONS_FORMICID
        { 567, "monkey.obj" }, // MONS_FORMICID_DRONE
        { 568, "monkey.obj" }, // MONS_FORMICID_VENOM_MAGE
        { 569, "monkey.obj" }, // MONS_RAIJU
        { 570, "monkey.obj" }, // MONS_DRAGON
        { 571, "monkey.obj" }, // MONS_SNAKE
        { 572, "monkey.obj" }, // MONS_MONSTROUS_DEMONSPAWN
        { 573, "monkey.obj" }, // MONS_GELID_DEMONSPAWN
        { 574, "monkey.obj" }, // MONS_INFERNAL_DEMONSPAWN
        { 575, "monkey.obj" }, // MONS_PUTRID_DEMONSPAWN
        { 576, "monkey.obj" }, // MONS_TORTUROUS_DEMONSPAWN
        { 577, "monkey.obj" }, // MONS_DEMONSPAWN_BLOOD_SAINT
        { 578, "monkey.obj" }, // MONS_CHAOS_CHAMPION
        { 579, "monkey.obj" }, // MONS_DEMONSPAWN_WARMONGER
        { 580, "monkey.obj" }, // MONS_DEMONSPAWN_CORRUPTER
        { 581, "monkey.obj" }, // MONS_DEMONSPAWN_SOUL_SCHOLAR
        { 582, "monkey.obj" }, // MONS_WORLDBINDER
        { 583, "monkey.obj" }, // MONS_GRAND_AVATAR
        { 584, "monkey.obj" }, // MONS_VINE_STALKER
        { 585, "monkey.obj" }, // MONS_DROWNED_SOUL
        { 586, "monkey.obj" }, // MONS_SHOCK_SERPENT
        { 587, "monkey.obj" }, // MONS_MANA_VIPER
        { 588, "monkey.obj" }, // MONS_NAGA_RITUALIST
        { 589, "monkey.obj" }, // MONS_NAGA_SHARPSHOOTER
        { 590, "monkey.obj" }, // MONS_SALAMANDER_FIREBRAND
        { 591, "monkey.obj" }, // MONS_SALAMANDER_MYSTIC
        { 592, "monkey.obj" }, // MONS_ASTERION
        { 593, "monkey.obj" }, // MONS_NATASHA
        { 594, "monkey.obj" }, // MONS_VASHNIA
        { 595, "monkey.obj" }, // MONS_BLOCK_OF_ICE
        { 596, "monkey.obj" }, // MONS_BLAZEHEART_GOLEM
        { 597, "monkey.obj" }, // MONS_SPELLSPARK_SERVITOR
        { 598, "monkey.obj" }, // MONS_OCTOPODE_CRUSHER
        { 599, "monkey.obj" }, // MONS_CRAB
        { 600, "monkey.obj" }, // MONS_GHOST_CRAB
        { 601, "monkey.obj" }, // MONS_TORPOR_SNAIL
        { 602, "monkey.obj" }, // MONS_MNOLEG_TENTACLE
        { 603, "monkey.obj" }, // MONS_MNOLEG_TENTACLE_SEGMENT
        { 604, "monkey.obj" }, // MONS_BENNU
        { 605, "monkey.obj" }, // MONS_USHABTI
        { 606, "monkey.obj" }, // MONS_DEATH_SCARAB
        { 607, "monkey.obj" }, // MONS_ANUBIS_GUARD
        { 608, "monkey.obj" }, // MONS_CAUSTIC_SHRIKE
        { 609, "monkey.obj" }, // MONS_ROBIN
        { 610, "monkey.obj" }, // MONS_SHARD_SHRIKE
        { 611, "monkey.obj" }, // MONS_SINGULARITY
        { 612, "monkey.obj" }, // MONS_SALAMANDER_STORMCALLER
        { 613, "monkey.obj" }, // MONS_ENTROPY_WEAVER
        { 614, "monkey.obj" }, // MONS_MOON_TROLL
        { 615, "monkey.obj" }, // MONS_MUTANT_BEAST
        { 616, "monkey.obj" }, // MONS_JUGGERNAUT
        { 617, "monkey.obj" }, // MONS_SPARK_WASP
        { 618, "monkey.obj" }, // MONS_DOOM_HOUND
        { 619, "monkey.obj" }, // MONS_DEEP_ELF_ELEMENTALIST
        { 620, "monkey.obj" }, // MONS_DEEP_ELF_ARCHER
        { 621, "monkey.obj" }, // MONS_DEMONIC_PLANT
        { 622, "monkey.obj" }, // MONS_WITHERED_PLANT
        { 623, "monkey.obj" }, // MONS_DART_SLUG
        { 624, "monkey.obj" }, // MONS_HOWLER_MONKEY
        { 625, "monkey.obj" }, // MONS_ANCESTOR
        { 626, "monkey.obj" }, // MONS_ANCESTOR_KNIGHT
        { 627, "monkey.obj" }, // MONS_ANCESTOR_BATTLEMAGE
        { 628, "monkey.obj" }, // MONS_ANCESTOR_HEXER
        { 629, "monkey.obj" }, // MONS_MELIAI
        { 630, "monkey.obj" }, // MONS_BAI_SUZHEN
        { 631, "monkey.obj" }, // MONS_BAI_SUZHEN_DRAGON
        { 632, "monkey.obj" }, // MONS_SALTLING
        { 633, "monkey.obj" }, // MONS_IMPERIAL_MYRMIDON
        { 634, "monkey.obj" }, // MONS_SERVANT_OF_WHISPERS
        { 635, "monkey.obj" }, // MONS_PEACEKEEPER
        { 636, "monkey.obj" }, // MONS_RAGGED_HIEROPHANT
        { 637, "monkey.obj" }, // MONS_HALAZID_WARLOCK
        { 638, "monkey.obj" }, // MONS_DREAM_SHEEP
        { 639, "monkey.obj" }, // MONS_FROG
        { 640, "monkey.obj" }, // MONS_BARACHI
        { 641, "monkey.obj" }, // MONS_BULTUNGIN
        { 642, "monkey.obj" }, // MONS_TEST_STATUE
        { 643, "monkey.obj" }, // MONS_FOXFIRE
        { 644, "monkey.obj" }, // MONS_MAGGIE
        { 645, "monkey.obj" }, // MONS_NAMELESS
        { 646, "monkey.obj" }, // MONS_ARMATAUR
        { 647, "monkey.obj" }, // MONS_BLOATED_HUSK
        { 648, "monkey.obj" }, // MONS_BUNYIP
        { 649, "monkey.obj" }, // MONS_GOLIATH_FROG
        { 650, "monkey.obj" }, // MONS_ELEIONOMA
        { 651, "monkey.obj" }, // MONS_FENSTRIDER_WITCH
        { 652, "monkey.obj" }, // MONS_WILL_O_THE_WISP
        { 653, "monkey.obj" }, // MONS_TEST_BLOB
        { 654, "monkey.obj" }, // MONS_DREAD_LICH
        { 655, "monkey.obj" }, // MONS_DEEP_ELF_AIR_MAGE
        { 656, "monkey.obj" }, // MONS_ARMOUR_ECHO
        { 657, "monkey.obj" }, // MONS_ROCKSLIME
        { 658, "monkey.obj" }, // MONS_VOID_OOZE
        { 659, "monkey.obj" }, // MONS_IRONBOUND_FROSTHEART
        { 660, "monkey.obj" }, // MONS_IRONBOUND_THUNDERHULK
        { 661, "monkey.obj" }, // MONS_IRONBOUND_BEASTMASTER
        { 662, "monkey.obj" }, // MONS_SALAMANDER_TYRANT
        { 663, "monkey.obj" }, // MONS_MLIOGLOTL
        { 664, "monkey.obj" }, // MONS_CACTUS_GIANT
        { 665, "monkey.obj" }, // MONS_CREEPING_INFERNO
        { 666, "monkey.obj" }, // MONS_SEARING_WRETCH
        { 667, "monkey.obj" }, // MONS_STOKER
        { 668, "monkey.obj" }, // MONS_QUICKSILVER_ELEMENTAL
        { 669, "monkey.obj" }, // MONS_CRYSTAL_ECHIDNA
        { 670, "monkey.obj" }, // MONS_PUTRID_MOUTH
        { 671, "monkey.obj" }, // MONS_TAINTED_LEVIATHAN
        { 672, "monkey.obj" }, // MONS_WENDIGO
        { 673, "monkey.obj" }, // MONS_NARGUN
        { 674, "monkey.obj" }, // MONS_HEADMASTER
        { 675, "monkey.obj" }, // MONS_LIVING_SPELL
        { 676, "monkey.obj" }, // MONS_WALKING_TOME
        { 677, "monkey.obj" }, // MONS_EARTHEN_TOME
        { 678, "monkey.obj" }, // MONS_CRYSTAL_TOME
        { 679, "monkey.obj" }, // MONS_DIVINE_TOME
        { 680, "monkey.obj" }, // MONS_FROSTBOUND_TOME
        { 681, "monkey.obj" }, // MONS_STRANGE_MACHINE
        { 682, "monkey.obj" }, // MONS_SPECTATOR
        { 683, "monkey.obj" }, // MONS_BOUND_SOUL
        { 684, "monkey.obj" }, // MONS_PHARAOH_ANT
        { 685, "monkey.obj" }, // MONS_STEELBARB_WORM
        { 686, "monkey.obj" }, // MONS_JOROGUMO
        { 687, "monkey.obj" }, // MONS_BROODMOTHER
        { 688, "monkey.obj" }, // MONS_CULICIVORA
        { 689, "monkey.obj" }, // MONS_SUN_MOTH
        { 690, "monkey.obj" }, // MONS_RADROACH
        { 691, "monkey.obj" }, // MONS_PARGHIT
        { 692, "monkey.obj" }, // MONS_JOSEPHINA
        { 693, "monkey.obj" }, // MONS_AMAEMON
        { 694, "monkey.obj" }, // MONS_LODUL
        { 695, "monkey.obj" }, // MONS_VV
        { 696, "monkey.obj" }, // MONS_ZENATA
        { 697, "monkey.obj" }, // MONS_METEORAN
        { 698, "monkey.obj" }, // MONS_GRUNN
        { 699, "monkey.obj" }, // MONS_STARFLOWER
        { 700, "monkey.obj" }, // MONS_SICKLY_MERFOLK_SIREN
        { 701, "monkey.obj" }, // MONS_MALARIOUS_MERFOLK_AVATAR
        { 702, "monkey.obj" }, // MONS_SKYSHARK
        { 703, "monkey.obj" }, // MONS_SLEEPCAP
        { 704, "monkey.obj" }, // MONS_CERULEAN_IMP
        { 705, "monkey.obj" }, // MONS_FORMLESS_JELLYFISH
        { 706, "monkey.obj" }, // MONS_JEREMIAH
        { 707, "monkey.obj" }, // MONS_BOULDER
        { 708, "monkey.obj" }, // MONS_ARCANIST
        { 709, "monkey.obj" }, // MONS_FLOATING_EYE
        { 710, "monkey.obj" }, // MONS_ANTIQUE_CHAMPION
        { 711, "monkey.obj" }, // MONS_KOBOLD_BLASTMINER
        { 712, "monkey.obj" }, // MONS_INUGAMI
        { 713, "monkey.obj" }, // MONS_PROTEAN_PROGENITOR
        { 714, "monkey.obj" }, // MONS_ASPIRING_FLESH
        { 715, "monkey.obj" }, // MONS_ONI
        { 716, "monkey.obj" }, // MONS_BOMBARDIER_BEETLE
        { 717, "monkey.obj" }, // MONS_WEEPING_SKULL
        { 718, "monkey.obj" }, // MONS_BURIAL_ACOLYTE
        { 719, "monkey.obj" }, // MONS_BLAZEHEART_CORE
        { 720, "monkey.obj" }, // MONS_MARTYRED_SHADE
        { 721, "monkey.obj" }, // MONS_ORC_APOSTLE
        { 722, "monkey.obj" }, // MONS_SACRED_LOTUS
        { 723, "monkey.obj" }, // MONS_THERMIC_DYNAMO
        { 724, "monkey.obj" }, // MONS_OBSIDIAN_BAT
        { 725, "monkey.obj" }, // MONS_PILE_OF_DEBRIS
        { 726, "monkey.obj" }, // MONS_PILLAR_OF_RIME
        { 727, "monkey.obj" }, // MONS_HOARFROST_CANNON
        { 728, "monkey.obj" }, // MONS_ELECTROFERRIC_VORTEX
        { 729, "monkey.obj" }, // MONS_POLTERGUARDIAN
        { 730, "monkey.obj" }, // MONS_MARROWCUDA
        { 731, "monkey.obj" }, // MONS_UNDYING_ARMOURY
        { 732, "monkey.obj" }, // MONS_XAKKRIXIS
        { 733, "monkey.obj" }, // MONS_HELLFIRE_MORTAR
        { 734, "monkey.obj" }, // MONS_GOD_WRATH_AVATAR
        { 735, "monkey.obj" }, // MONS_SHADOW_PUPPET
        { 736, "monkey.obj" }, // MONS_SHADOW_PRISM
        { 737, "monkey.obj" }, // MONS_SOUL_WISP
        { 738, "monkey.obj" }, // MONS_GLOBE_OF_ANNIHILATION
        { 739, "monkey.obj" }, // MONS_FRAVASHI
        { 740, "monkey.obj" }, // MONS_NEKOMATA
        { 741, "monkey.obj" }, // MONS_CLOCKWORK_BEE
        { 742, "monkey.obj" }, // MONS_CLOCKWORK_BEE_INACTIVE
        { 743, "monkey.obj" }, // MONS_DIAMOND_SAWBLADE
        { 744, "monkey.obj" }, // MONS_PLATINUM_PARAGON
        { 745, "monkey.obj" }, // MONS_WALKING_ALEMBIC
        { 746, "monkey.obj" }, // MONS_MONARCH_BOMB
        { 747, "monkey.obj" }, // MONS_BOMBLET
        { 748, "monkey.obj" }, // MONS_SPLINTERFROST_BARRICADE
        { 749, "monkey.obj" }, // MONS_SEISMOSAURUS
        { 750, "monkey.obj" }, // MONS_SEISMOSAURUS_EGG
        { 751, "monkey.obj" }, // MONS_PHALANX_BEETLE
        { 752, "monkey.obj" }, // MONS_RENDING_BLADE
        { 753, "monkey.obj" }, // MONS_SHADOW_TURRET
        { 754, "monkey.obj" }, // MONS_ALDERKING
        { 755, "monkey.obj" }, // MONS_ONI_INCARCERATOR
        { 756, "monkey.obj" }, // MONS_WYRMHOLE
        { 757, "monkey.obj" }, // MONS_SPHINX
        { 758, "monkey.obj" }, // MONS_SPHINX_MARAUDER
        { 759, "monkey.obj" }, // MONS_HAUNTED_ARMOUR
        { 760, "monkey.obj" }, // MONS_POLTERGEIST
        { 761, "monkey.obj" }, // MONS_VAMPIRE_BLOODPRINCE
        { 762, "monkey.obj" }, // MONS_REVENANT
        { 763, "monkey.obj" }, // MONS_NAMELESS_REVENANT
        { 764, "monkey.obj" }, // MONS_PETRIFIED_FLOWER
        { 765, "monkey.obj" }, // MONS_SOLAR_EMBER
        { 766, "monkey.obj" }, // MONS_GOBLIN_RIDER
        { 767, "monkey.obj" }, // MONS_IRONBOUND_MECHANIST
        { 768, "monkey.obj" }, // MONS_SPROZZ
    };

    spdlog::debug("getModelFileForType: name='{}' type={} btype={}",
        mon.name(), mon.type(), mon.btype());

    auto it = s_typeModelMap.find(mon.type());
    if (it != s_typeModelMap.end())
        return it->second;
    return s_defaultModel;
}
